apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      service: api-gateway
  template:
    metadata:
      labels:
        service: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: api-gateway:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 8070
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  selector:
    service: api-gateway
  ports:
  - port: 8070
    targetPort: 8070
  type: LoadBalancer
