apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-service
spec:
  selector:
    matchLabels:
      service: consumer-service
  template:
    metadata:
      labels:
        service: consumer-service
    spec:
      containers:
      - name: consumer-service
        image: consumer-service:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8071
---
apiVersion: v1
kind: Service
metadata:
  name: consumer-service
spec:
  selector:
    service: consumer-service
  ports:
  - port: 8071
    targetPort: 8071
  type: LoadBalancer
