apiVersion: apps/v1
kind: Deployment
metadata:
  name: gofoody-app
spec:
  selector:
    matchLabels:
      service: gofoody-app
  template:
    metadata:
      labels:
        service: gofoody-app
    spec:
      containers:
      - name: gofoody-app
        image: gofoody-app:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gofoody-app
spec:
  selector:
    service: gofoody-app
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer
