apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
spec:
  selector:
    matchLabels:
      service: restaurant-service
  template:
    metadata:
      labels:
        service: restaurant-service
    spec:
      containers:
      - name: restaurant-service
        image: restaurant-service:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8074
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  selector:
    service: restaurant-service
  ports:
  - port: 8074
    targetPort: 8074
  type: LoadBalancer
